# Generated by Django 2.2.3 on 2022-10-05 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='estadogestion',
            fields=[
                ('idEstadoGestion', models.AutoField(primary_key=True, serialize=False)),
                ('estadoGestionNombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('estadoGestionDescripcion', models.CharField(max_length=125, verbose_name='Descripción')),
                ('estadoGestionActivo', models.CharField(max_length=1, verbose_name='Estado')),
            ],
        ),
    ]
