# Generated by Django 2.2.3 on 2022-10-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20221007_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategoria',
            name='Categoria_idCategoria',
            field=models.IntegerField(verbose_name='Categoria'),
        ),
    ]
