# Generated by Django 2.2.3 on 2022-10-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20221007_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategoria',
            name='Categoria_idCategoria',
            field=models.IntegerField(verbose_name='Categoria'),
        ),
    ]
