# Generated by Django 2.2.3 on 2022-10-14 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20221007_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('usuarioNombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('usuarioApellido', models.CharField(max_length=45, verbose_name='Apellido')),
                ('usuarioTipoDocumento', models.CharField(max_length=45, verbose_name='Tipo de Documento')),
                ('usuarioNumeroDocumento', models.IntegerField(max_length=20, verbose_name='Numero de Documento')),
                ('usuarioClave', models.CharField(max_length=45, verbose_name='Contraseña')),
                ('usuarioCorreo', models.CharField(max_length=65, verbose_name='Correo')),
                ('usuarioRol', models.CharField(max_length=45, verbose_name='Rol usuario')),
                ('usuarioActivo', models.CharField(blank=True, max_length=1, verbose_name='Estado')),
            ],
        ),
    ]
