# Generated by Django 2.2.3 on 2022-10-27 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_gestion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gestion',
            new_name='ServicioOfrecido',
        ),
    ]
