# Generated by Django 2.2.3 on 2022-10-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20221027_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='usuarioNumeroDocumento',
            field=models.IntegerField(verbose_name='Numero de Documento'),
        ),
    ]
