# Generated by Django 2.2.3 on 2022-11-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20221027_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='GestionCliente',
            fields=[
                ('idGestionCliente', models.AutoField(primary_key=True, serialize=False)),
                ('gestionClienteRegistro', models.DateTimeField(verbose_name='Registro')),
                ('gestionClienteObservacion', models.CharField(blank=True, max_length=254, verbose_name='Observacion')),
                ('gestionClienteTiempoInvertido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Tiempo')),
                ('EstadoGestion_idEstadoGestion', models.IntegerField(verbose_name='Estado')),
                ('Subcategoria_idSubcategoria', models.IntegerField(verbose_name='idSubcategoria')),
                ('Usuario_idUsuario', models.IntegerField(verbose_name='Usuario')),
                ('Cliente_idGestionCliente', models.IntegerField(verbose_name='idGestionCliente')),
            ],
        ),
    ]
