# Generated by Django 2.2.3 on 2022-11-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_gestioncliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aunditoria',
            fields=[
                ('ididAuditoria', models.AutoField(primary_key=True, serialize=False)),
                ('auditoriaNombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('auditoriaDescripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('auditoriaRegistro', models.DateTimeField(verbose_name='Fecha de Registro')),
                ('Usuario_idUsuario', models.IntegerField(verbose_name='Usuario')),
                ('GestionCliente_idGestionCliente', models.IntegerField(max_length=11, verbose_name='Estado')),
            ],
        ),
        migrations.AlterField(
            model_name='gestioncliente',
            name='Cliente_idGestionCliente',
            field=models.IntegerField(verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='gestioncliente',
            name='Subcategoria_idSubcategoria',
            field=models.IntegerField(verbose_name='Subcategoria'),
        ),
        migrations.AlterField(
            model_name='gestioncliente',
            name='gestionClienteRegistro',
            field=models.DateTimeField(verbose_name='Fecha de Registro'),
        ),
    ]
