# Generated by Django 2.2.3 on 2022-11-02 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20221102_1515'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aunditoria',
            new_name='Auditoria',
        ),
    ]
