# Generated by Django 2.2.3 on 2022-11-02 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20221102_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditoria',
            old_name='ididAuditoria',
            new_name='idAuditoria',
        ),
    ]
