# Generated by Django 2.2.3 on 2022-12-04 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_servicioofrecido'),
        ('main', '0015_auto_20221102_1521'),
    ]

    operations = [
    ]
