# Generated by Django 3.0 on 2022-12-04 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_merge_20221204_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='-', max_length=150, verbose_name='Correo'),
        ),
    ]
